name: Deploy Apache Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2

      - name: Copy website files to Apache root
        run: |
          sudo cp -r ./* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/

      - name: Start Apache service
        run: |
          sudo systemctl start apache2
          sudo systemctl status apache2

      - name: Verify Apache is running
        run: curl -I http://localhost